### ISSUE TITLE
Generate ARM types from specification schemas using the type provider

### ISSUE THREAD

**Issue by xperiandri** [CompositionalIT/farmer#1143]
https://github.com/florenzen/JsonSchemaProvider builds some foundation that allows producing types from JSON schemas.
It is not possible to use it as is but it can be modified to achieve desired result.

Trying to support compatibility with the latest API manually takes too many resources and does not seem like a sustainable approach.

**Comment by isaacabraham** [comment]
Per our discussion offline, we should create a discussion rather than an issue for this here. The issues with the schema are that, frankly, they can't be relied upon and generally do not provide an acceptable level of safety that I would expect to see. In a dynamic / hybrid typed system that may be acceptable, but in a static type system we can't have a generated schema that only works some of the time.

I get the point you're making re: extra effort to manually modify the schema - I'm just not sure what the solution is.

**Comment by isaacabraham** [comment]
@xperiandri If you would like to convert this to a discussion, that would be great.
