### ISSUE TITLE
consider changing `depends_on` to take the object itself instead of name

### ISSUE THREAD

**Issue by et1975** [CompositionalIT/farmer#167]
The burden of finding the right property can be lifted from the user, whether it's a name, ID or resource path can be determined by the operation itself. 

Freya DSL does something similar with a bit of SRTP magic.

**Comment by isaacabraham** [comment]
I was actually thinking about this today. Unfortunately I don't think SRTPs would suffice because the actual name of the resource is not always the "Name" property e.g. for the Sql Config, it's the ServerName that matters. We could add this onto the IBuilder interface, but that's just one more thing for authors to implement I think. Hmmmm.
