### ISSUE TITLE
Smoother workflow when writing docs

### ISSUE THREAD

**Issue by hravnx** [CompositionalIT/farmer#175]
At the moment the documentation source lives in a separate branch, imaginatively called `docs`. 

So adding features with docs consists of these steps:

1) Fork/pull master
2) Code feature and tests
3) Commit, push and create PR for feature
4) Pull docs
5) Write docs
6) Commit, push and create PR for feature

While not especially difficult or bad, it does seem suboptimal. More importantly, perhaps, it signals a separation between docs and features, where (IMHO) the two should go together - it makes it much easier to discuss a feature if the docs are part of the PR for that feature. 

I'm not an expert in Hugo, but from looking at the GH actions defines for deploying docs, it seems like the following should be feasible:

1) Move documentation source away from the `docs` branch and into master, in a folder called .... *drumroll* .... `docs`. 
2) Move all Hugo configuration into that folder as well, in effect making the docs folder be a fully self-contained Hugo site.
3) Change the documentation deploy job to be something like:
  a. Copy files from the `docs` folder in master in to the working directory of a CI agent.
  b. Run Hugo build step against that folder
  c. Push the build output into the gh-pages branch (like it is done today)
  
Are there any obvious reasons that I'm missing for why the docs and code are kept separate, and/or something like the above is impossible?

**Comment by isaacabraham** [comment]
The historical reason is: when I started, I had no clue about hugo and started on a separate branch as an experiment. It's still there. I know that when @SeanKilleen did this work we discussed merging them - I'm not sure if there was anything holding us back on that?

Definitely happy to do this as it'll make it easier to keep them in sync.

**Comment by SeanKilleen** [comment]
@isaacabraham I don't think anything is holding us back from doing this. It was one of the options I presented way back when and I think we'd just happened to go a different way (note to self: document decisions like this within the PR in the future :smile: )

@hravnx do you want to take a crack at a PR for it? Otherwise I'm happy to. Docs folder on master is my preference as well.

**Comment by SeanKilleen** [comment]
Found a historical mention of these options: https://github.com/CompositionalIT/farmer/issues/84#issuecomment-609498633

I think the docs were in a docs branch prior to my involvement, and we kept it that way for inertia's sake.

**Comment by hravnx** [comment]
I can certainly take a look at it, and come up with an attempt, but I will likely need help when it comes to testing it.

**Comment by SeanKilleen** [comment]
@hravnx ping me whenever you've got your PR ready and I'll check it out. 👍

**Comment by isaacabraham** [comment]
Aha! I think that that last point was the key. This would mean that we might need to think about comparing the release of docs to the release of code.

Might it be worth having a docs branch which is simply branches off of master, and that this branch would be what GH docs runs off of? That way, whenever we do a proper release (nuget), we can choose to merge the docs then?

Or am I just complicating things for no real gain?

**Comment by SeanKilleen** [comment]
@isaacabraham 

> Or am I just complicating things for no real gain?

IMO, yes. :) 

The way I see it, if you have a GitHub issue, and you submit a PR against it for code, you could either include docs in that PR, or submit a separate PR mentioning it. That doesn't require a separate docs branch and a separate branch could actually complicate it. Plus, the docs "branch" isn't an actual real branch off of the code, but is currently being treated like a separate mini repo, which IMO is not really in line with how git would intend those things to work.

I wouldn't worry about a methodical dream of keeping the docs & code in sync. Although, when you tag a release on the master branch, in this new way of doing things, the docs would also be captured as part of that tag at that point in time, which is nice. 

I think @hravnx's suggested approach simplifies things and makes the docs visible in a folder rather than a branch that someone has to know exists. I'd suggest going to there and then complicating if need be.

**Comment by hravnx** [comment]
I will not have time to look at it before later in the week. So if you’re impatient, have at it :-)

**Comment by isaacabraham** [comment]
Let's do it then. No rush - for now it works fine.

**Comment by isaacabraham** [comment]
@hravnx this seems to work :-) @SeanKilleen is there a way in GH actions to only get an action to fire if a file in a specific path has changed? Currently it rebuilds on any change to master.

**Comment by hravnx** [comment]
https://github.blog/changelog/2019-09-30-github-actions-event-filtering-updates seems relevant

**Comment by SeanKilleen** [comment]
@hravnx @isaacabraham one moment, I'll submit a PR.

**Comment by isaacabraham** [comment]
@SeanKilleen @hravnx I've busted it again. I *think* it's related [this commit](https://github.com/CompositionalIT/farmer/commit/a485cde1c3522fa411e08ede8220428d16fb549e), where I have added the submodule in or something. I actually have no clue what that's done but suddenly now the action [isn't working](https://github.com/CompositionalIT/farmer/actions/runs/123554477).

Any ideas? Note - the theme is a fork of the official one because I made some changes to it (image logo etc.) so it needs to point to the CIT fork of the theme.

**Comment by hravnx** [comment]
Playing devil’s advocate for a second: why does it have to be a sub module, if you have modified it anyway? Why not just copy the files into the main farmer repo? 

In my experience, Git submodules leads to much confusion and problems that are many times worse than the problem they’re trying to solve.

**Comment by isaacabraham** [comment]
Great question. I just copied the original process from the Hugo docs - so basically just cargo cult copy and paste. If we can do away with the submodule and put the theme directly in, that would be my preference.

**Comment by SeanKilleen** [comment]
We had issues with submodules back in the beginning and removed them from the process.

If memory serves, we were able to specify a theme which would load it remotely, and we were able do overrides locally so that when a theme needed to be overriden, we'd just place that one modified file in a local directory.

I will try to find where I'd documented this during the original process and see if my memory is right.

**Comment by isaacabraham** [comment]
Awesome. Any reason why we can't just copy the whole theme across - I suppose the main issue is then that updates to the theme would become a manual process?

**Comment by SeanKilleen** [comment]
OK, I figured it out -- my memory was incorrect actually, and submodules is the way things are done there. FWIW I don't recommend copying all the files; nightmare to keep up. I'd look into seeing if you can do remote theming and overrides without the sub-module, but you should be able to use the submodule without modifying it, only making changes to local layout files.

The issue: When we moved from the `docs` branch to a folder on the `master` branch, we didn't remove the old submodule, which has to be done explicitly or also mapped in the `.gitmodules` file. 

The error is subtly confusing because it's actually referring to the old submodule location in the docs branch: 

> No url found for submodule path 'themes/hugo-theme-learn' in .gitmodules

The solution I believe is to remove that old submodule reference by running something like:

```cmd
git rm --cached themes/hugo-theme-learn
```

And pushing. At that point, the old submodule will be gone, the new one will be mapped, and things should work OK.

@isaacabraham give that a shot and push it and let me know how it goes.

**Comment by isaacabraham** [comment]
Done. Don't know how to kick off another action run though!

**Comment by SeanKilleen** [comment]
@isaacabraham AFAIK you need to make a change to the code; last time I checked GH Actions, unfortunately, does not yet support manual re-tries or manual starts of actions.

**Comment by isaacabraham** [comment]
Works! Thanks.
