### ISSUE TITLE
Support static web hosting in Azure Storage

### ISSUE THREAD

**Issue by panesofglass** [CompositionalIT/farmer#180]
[Docs](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website)

Static hosting is surprisingly nothing more than creating a StorageV2 account, then enabling static hosting. Enabling static hosting creates a container called `$web` where the static site files are to be deployed. This support could allow a user to specify a zip to upload to that container so that it's ready to go.

Unfortunately, it appears you need to use [Azure  CLI](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-cli) or [PowerShell](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-powershell). See [1](https://github.com/sjkp/azure-arm-static-webpage#enabling-azure-static-web-pages), [2](https://stackoverflow.com/a/51149447/13289748), and [3](http://www.frankysnotes.com/2019/03/deploy-automatically-static-website.html). It seems the new [`Azure.Storage.Blobs.BlobServiceClient.SetPropertiesAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.setpropertiesasync?view=azure-dotnet#Azure_Storage_Blobs_BlobServiceClient_SetPropertiesAsync_Azure_Storage_Blobs_Models_BlobServiceProperties_System_Threading_CancellationToken_) can also achieve the desired outcome.

Options:
- [ ] Generate ARM template for storage account and Azure Container Instance to run azure-cli
- [ ] Generate ARM template for storage account and generate a F# script to update the blob service properties
- [ ] Do nothing and allow the user to determine how to set this up after running the ARM template

**Comment by isaacabraham** [comment]
@panesofglass The Azure CLI option isn't really a problem since we already support shelling out to the CLI, so this could just be a PostDeployAction. The same could apply for uploading the content - just part of the same PostDeployAction. I don't think we should generate an F# script for this - it can be done directly through the Farmer deploy process. See [here](https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Arm/Web.fs#L127) for how it works with the Web App (although I can't remember why I put this onto the ARM resource itself rather than the builder - feel wrong to me).

**Comment by isaacabraham** [comment]
@panesofglass can this be closed now given #282?

**Comment by panesofglass** [comment]
Looks good to me!
