### ISSUE TITLE
Consider merging duplicate resources? How to pick the "right" one?

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#24]

**Comment by Dzoukr** [comment]
Just a quick thought on this. I love Farmer for one reason - it is _simple_. Simple to use, simple to compose - just friendly DSL. But I would avoid making it too smart. If you want to automate infrastructure on Azure, you still need a lot of knowledge (and self-control) anyway and I think no tool can help you with that really. Instead of some merging I would simply set some kind of "last added duplicit resource is used", document it and that's it. Maybe emit some warning to console "your template has duplicit resource XYZ", but keep it simple.

What do you think?

**Comment by isaacabraham** [comment]
That's basically what we do already: https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Builders.Arm.fs#L56

I'm just wondering if there should be some way to pick more intelligently. Or, provide a warning / error, yes.

Just something that is consistent, easy to understand and obvious to the user.
