### ISSUE TITLE
custom_script_files option doesn't seem to work

### ISSUE THREAD

**Issue by pviotti** [CompositionalIT/farmer#319]
Hi there - I was trying to upload a script file to my vm using the `custom_script_files` option as follows:

```fsharp
    let myVm = vm {
        name vmResourceName
        username vmUsername
        vm_size Vm.Standard_B2s
        operating_system (Vm.makeLinuxVm "0001-com-ubuntu-server-focal" "canonical" "20_04-lts")
        os_disk 64 Vm.Premium_LRS
        diagnostics_support
        domain_name_prefix (Some vmHostname) 
        custom_script_files [ "https://gist.githubusercontent.com/blablabla/setup-vm.sh" ]
    }
```

but the script file URI doesn't make it to the ARM template file.  
Does it work only with Windows VMs..? Am I missing something?

(Thanks for Farmer btw, it's a pretty handy project!)

**Comment by isaacabraham** [comment]
@pviotti You have to set the *name* of the custom script:

```fsharp
    let myVm = vm {
        name vmResourceName
        username vmUsername
        vm_size Vm.Standard_B2s
        operating_system (Vm.makeLinuxVm "0001-com-ubuntu-server-focal" "canonical" "20_04-lts")
        os_disk 64 Vm.Premium_LRS
        diagnostics_support
        domain_name_prefix (Some vmHostname) 
        custom_script "setup" // add this line
        custom_script_files [ "https://gist.githubusercontent.com/blablabla/setup-vm.sh" ]
    }
```

Basically, this becomes the name of the script resource in the ARM template. Without it, we ignore the script files.

The fact that you've fallen for this suggests that the API isn't obvious to figure out. We could do one of several things:

1. Throw an error if you provide files without a name (or vice versa). This would have probably been enough for you on this occasion.
2. Change the API so that you have to supply the name *and* the files together:
```fsharp
        custom_script_files "setup" [ "https://gist.githubusercontent.com/blablabla/setup-vm.sh" ]
```
3. We could make this optional and look at setting an automatically generated name for this instead. However, I'm not sure if the resource name has restrictions or must be unique etc.

**Comment by isaacabraham** [comment]
P.S. It should work for both Linux and Windows.

**Comment by isaacabraham** [comment]
@pviotti ignore what I said before. It was nonsense and I've deleted the comment. I've just had another look through the source code and now remember how this works in Azure.

* The custom script files are simply what files to copy up onto the VM.
* You still have to supply a script that is *executed* on the VM, which may use those files.

The way we do that in Farmer is through the `custom_script` keyword e.g.

```fsharp
let myVm = vm {
        name vmResourceName
        custom_script "sh setup-vm.sh" // you have to actually *call* the script!
        custom_script_files [ "https://gist.githubusercontent.com/blablabla/setup-vm.sh" ]
    }
```

The reason why the two commands are separate is because you could simply pass the entire command in the `custom_script` rather than in files that you call.

I'm going to add a validation error so that if you supply files but no script, we fail fast with a sane error message.

**Comment by pviotti** [comment]
ok, thanks for the explanation! I'll try again.

> The reason why the two commands are separate is because you could simply pass the entire command in the custom_script rather than in files that you call.

makes sense. (I also got confused because if you search for "script to run upon deployment on Azure vm", you find [this page](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux#property-script) that talks about an inline script that has to be supplied base64 encoded...)

> I'm going to add a validation error so that if you supply files but no script, we fail fast with a sane error message.

sounds good. I'd also suggest to expand a bit [the docs](https://github.com/CompositionalIT/farmer/blob/docs/content/api-overview/resources/virtual-machine.md) (maybe add an ad-hoc example) (maybe I will submit a PR..).

**Comment by isaacabraham** [comment]
A PR would be gratefully accepted :-)

**Comment by isaacabraham** [comment]
If you're happy with this error message i.e. it would have explained to you what to do, I'll merge it in. https://github.com/CompositionalIT/farmer/pull/321/files#diff-d1f245ce5e20f91fe6c13181aac49db3R126

**Comment by pviotti** [comment]
the error message looks good, and the custom script works, thank you. Here's the PR for the docs improvement: https://github.com/CompositionalIT/farmer/pull/322
