### ISSUE TITLE
Web App support for ASP .NET Core Site Extension

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#373]
There is apparently a site extension that does magic stuff with logging for .NET Core apps.

https://www.visualstudiogeeks.com/devops/installing-aspnet-core-site-extensions-for-azure-app-service-using-arm

We should turn this on by default in Farmer.

**Comment by raymens** [comment]
You mean by default or by default when the .NET Core stack is selected in `runtime_stack`?

**Comment by isaacabraham** [comment]
@raymens yes, I presume so. I would like to know what's required for non-net core apps as well to automatically get tracing writing out - I can't find much docs on this.

**Comment by davedawkins** [comment]
Any idea what the extension is called? The only extension I can find (contains word 'log') from `App Services -> MyApp -> Extensions -> Add` is a very pedestrian-looking `ASP.NET Core Logging Integration`

**Comment by davedawkins** [comment]
It looks promising actually. This ring any bells?
https://mderriey.com/2020/08/08/a-look-at-the-aspnet-core-logging-provider-for-app-service/

**Comment by davedawkins** [comment]
I'm actively working on this. Here's my progress so far:
- The extension @isaacabraham  references is probably `Microsoft.AspNetCore.AzureAppServices.SiteExtension`
- Additional useful resources
https://www.phillipsj.net/posts/applying-azure-app-service-extensions-with-arm/
https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2020-06-01/sites/siteextensions
- I'm implementing a two-level solution
  1. Add a *general* `use_extension` command to the `webApp` builder. This will allow easy addition of any extension
  2. Enable the logging extension by injecting the `use_extension` configuration accordingly

Eg
```
let app = webApp {
        name "my_app"
        use_extension "Microsoft.AspNetCore.AzureAppServices.SiteExtension"
}

let deployment = arm {
    location Location.NorthEurope

    add_resource app
}
```

Some things I'm not sure about:
- Extensions appear to require only a single argument (their name/ID) in order to be included in a deployment, however there are additional properties on offer, such as `location` and `properties.version`. I think an additional enhancement to this work may be a builder named `siteExtension` than can be passed to `add_resource`, where more detailed configuration can be specified. By default, I'm using the same location as the main app when generating the resource.
- My implementation for `use_extension` currently looks like this
```
[<CustomOperation "use_extension">]
    member this.UseExtension(state:WebAppConfig, name:string) =
        let state = this.SystemIdentity (state) 
        { state with SiteExtensions = { Name = name; Location = None } :: state.SiteExtensions }
```
I'm not sure if SystemIdentity is needed. It's there because one of the referenced articles on using siteExtensions arguably implied it should be there. I don't know enough about Azure to even know where to start looking if that's true or not.

----
Currently testing by deploying one of my own SAFE projects to see if Azure barfs on the generated template. Also working on unit tests.

----
### Ignore this bit if you like!

An F# style issue. I have a configuration type that ideally I would like to look like this
```
type SiteExt = {
    Name : string
    Location : Location option
    // Version : Version option
   // etc
}
```
However constructors for this end up looking like this `{ Name = "xx"; Location = loc }`. Seeing that is in fact a `SiteExt` is completely opaque. Even mouse-over intellisense can't help much. I considered this definition
```
type SiteExt = {
    ExtensionName : string
    Location : Location option
}
```
This at least gives me context but I guess is just the same as doing `{ SiteExt.Name = ".." ... }`. Even the addition eventually of `Version` provides little clue as to what we're building.

This might only be a problem because I have created type `SiteExt` as an intermediate configuration separate to the `SiteExtension` type which is an implementation of `'IArmResource`, and they both have similarly named field names. I wasn't sure I had enough context to construct them immediately (SiteExt is like a parse tree node, SiteExtension is like the generated code).

I'd appreciate an experienced perspective that balances being idiomatic, readable and which would produce code ScottW would be proud of. :-)
