### ISSUE TITLE
v1.3.0-beta1 - unable to link to unmanaged external service plan

### ISSUE THREAD

**Issue by TheRSP** [CompositionalIT/farmer#455]
When deploying the following farmer script (ARM template below), I get an error "Cannot find ServerFarm with name my-asp-name.". I believe this is beause in the ARM template, `$.resources[0].properties.serverFarmId` is the simple name of the resource 'my-asp-name' rather than the full reference including the resource group: `[resourceId('my-asp-resource-group', 'Microsoft.Web/serverfarms', 'my-asp-name')]`.

I believe this has been caused by the ResourceId changes. Previously, I was using a custom ARM expression as the input to `link_to_unmanaged_service_plan ` but in the latest version, this overload no longer exists. How would I achieve the desired result in this case?

```fs
#r "nuget: Farmer, Version=1.3.0-beta1"

open Farmer
open Farmer.CoreTypes
open Farmer.Builders

let asp = ResourceId.create ("my-asp-name","my-asp-resource-group")
let myApp  = webApp {
    name "my-web-app"
    app_insights_off
    link_to_unmanaged_service_plan asp
}

let deployment = arm {
    add_resource myApp
}

deployment
|> Writer.quickWrite "myFirstTemplate"
```
```diff
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "outputs": {},
  "parameters": {},
  "resources": [
    {
      "apiVersion": "2016-08-01",
      "dependsOn": [],
      "identity": {
        "type": "None"
      },
      "kind": "app",
      "location": "westeurope",
      "name": "my-web-app",
      "properties": {
        "httpsOnly": false,
+       "serverFarmId": "my-asp-name",
-       "serverFarmId": [resourceId('my-asp-resource-group', 'Microsoft.Web/serverfarms', 'my-asp-name')]
        "siteConfig": {
          "alwaysOn": false,
          "appSettings": [],
          "connectionStrings": [],
          "metadata": [
            {
              "name": "CURRENT_STACK",
              "value": "dotnetcore"
            }
          ]
        }
      },
      "tags": {},
      "type": "Microsoft.Web/sites"
    }
  ]
}
```

**Comment by isaacabraham** [comment]
Hey. I can see [why this is happening now](https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Arm/Web.fs#L116). The reference ServicePlan is still being stored as a raw "resource name" at the ARM level.

Basically beforehand this was an arbitrary ARM expression which was the wrong way to do it. The builder is doing the right thing - requesting you to provide a full service farm reference (incidentally, the "proper" way to do it is as follows: `ResourceId.create (Arm.Web.serverFarms, ResourceName "my-asp-name", "my-asp-resource-group")`).

But we're (incorrectly) throwing away the "full" resource id details once we get to the ARM layer, and just emitting the name only!

This is a quick fix to make and I can push out a release for this. In the meantime, if you construct that same ARM expression as you did before, and set that as the "name" of the resource id (i.e. instead of just `my-asp-name`) then this might fix it.

**Comment by isaacabraham** [comment]
Releases as 1.3.0-beta2

**Comment by TheRSP** [comment]
Thanks for the super-quick turn around on this one 🥇
