### ISSUE TITLE
Comparison to Azure Management Libraries

### ISSUE THREAD

**Issue by ZenoArrow** [CompositionalIT/farmer#46]
I think this is a great project, and a month or so ago I'd have been all over it, but as Microsoft already provide libraries to manage ARM resources from code, I'm wondering how Farmer compares.

If you don't know what I'm talking about, and I wouldn't blame you as Microsoft haven't heavily promoted it, I'm talking about the Azure Management Libraries:
https://github.com/Azure/azure-libraries-for-net

Thanks in advance.

**Comment by isaacabraham** [comment]
@ZenoArrow Hey. Yes, I (think!) I know what the Azure libraries are. I think that they're a bit different:

* Farmer generates ARM templates.
* The Azure Libraries go directly to the Azure REST APIs.

As such, Farmer lives "on top" of ARM, including things like the Azure CLI, DevOps tooling etc.. If you're already using ARM templates, Farmer is a natural option because it simply makes it quicker to create the templates that you would have already been using. If you're not using ARM already, then you can think about comparing ARM in general with Azure .NET SDK in terms of deployment capabilities etc.

This table might provide some more guidance and help you choose:

| | Farmer | Azure .NET SDK |
|-|-|-|
| Bundled Deployment | Use ARM tooling e.g. Azure CLI or .NET SDK | Built-in |
| SDK | Lightweight (single NuGet package) | Complex (loads of packages with dozens of dependencies) |
| Programatic authoring | Yes | Yes |
| Idempotent Deployment | Yes | No (I think!) |
| Coverage | Popular Azure resources (~ 10) | Lots of Azure resources |

Hope that helps!

**Comment by ZenoArrow** [comment]
Thanks for the feedback. Regarding the simplicity of the libraries, I agree it's nice to have a single package to deal with as there are a ton of packages with the Azure Management Libraries, though in practice a user just has to specify one, as Microsoft.Azure.Management.Fluent (https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) is a meta-package for the related package, so you really only have to specify that one. Regarding idempotency, it's hard for me to comment on this as I'm still getting used to how things fit together, but it wouldn't surprise me if this was taken care of. Something I thought you might be interested in is that there may be ways for the libraries to compliment each other. As a simple example of this, if you ever chose to offer a "compile to ARM + deploy" as a single step, this could be complimented with a progress indicator:

https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template-with-progress/blob/master/Program.cs

In any case, best of luck, and thanks again.

**Comment by isaacabraham** [comment]
@ZenoArrow 

Thanks for the feedback :-) And Farmer already supports a "compile to ARM and deploy" as a single step :-)

```fsharp
deploy |> Writer.quickDeploy "my-resource-group"
```

although it relies on the Azure CLI to do the bulk of the heavy lifting.
