### ISSUE TITLE
Function App: Support for 64 bits

### ISSUE THREAD

**Issue by Iamabdul** [CompositionalIT/farmer#528]
Based on the [latest commit ](https://github.com/CompositionalIT/farmer/commit/f0bd5ba32b477d6a61a5842f42bec3544b934cba) for supporting 64 bit worker process in web apps, can we also do the same for function apps?

I can see that the template for the functions also use "use32BitWorkerProcess" in it's json, and based on the work already done for web apps, is the only thing left for functions is to expose it on the functions builder and create it's CustomOperation?

Thanks you!

**Comment by isaacabraham** [comment]
@Iamabdul yes, we definitely can. The proper way to do this since 1.4.0b1 is to move the existing web app keyword into the extensions on `IServiceAppPlan` (at the bottom of `Builders.WebApp.fs`, add the appropriate field onto `CommonWebConfig` and then implement the copying to / from in the implementations of `IServiceAppPlan` for both WebApp and Functions builders. Then you'll get the keyword for free and it's clear that there's shared behaviours.
