### ISSUE TITLE
Question: what is overwritten when redeploying to the same domain (and is there a way not to)?

### ISSUE THREAD

**Issue by Lewiszz** [CompositionalIT/farmer#639]
Hi!

This is not a feature request, just a question on what Farmer can(not) do and how. My knowledge of ARM is not that extensive, please forgive me for any stupid questions.

I have been using an ARM template to deploy my web app. I've manually configured the web app to link to a custom domain and assigned an SSL certificate to it. When redeploying using the correct pricing tier, my web app content would be updated but all settings (connection strings, custom domains, SSL certificates) remained as they were.

I now want to move to Farmer, but in my own Farmer tests so far, it seems as if these settings are overwritten when I redeploy. I have only tested the connection string so far. I know that connection strings can also be supplied through the Farmer script, so that's not an issue per se. But I am afraid that when I redeploy to my live website, my custom domain and SSL certificate settings will also disappear.

Is this true? That the custom domains and SSL certificates will be overwritten by default? If so, is there something I can do to overcome this? Or is there a way to configure my Farmer script so that it sets custom domains and SSL certificates everytime it deploys, just like the connection string?

Or am I trying to do something that I shouldn't want? :) 

FYI this is the script I am using at the moment:

```fsharp
let web = webApp {
    name "name-of-my-app"
    sku WebApp.Sku.B1
    setting "SOME_SETTING" "xxxx"
    zip_deploy "deploy"
}
let deployment = arm {
    location Location.WestEurope
    add_resource web
}

deployment
|> Deploy.execute "name-of-my-resource-group" Deploy.NoParameters
|> ignore
)
```

PS Also please let me know if this is not the right place to ask this.

**Comment by isaacabraham** [comment]
Hi @Lewiszz. I would test those two specific bits out if possible.

There are a couple of other things you can do:

1. Create a test website with a cert on and / or custom domain and deploy a template like that of above.
2. Try the `whatIf` command on Deploy instead of `execute`, which will return a list of actions it'll do if you were to deploy the template.
3. You can try the above manually as well by first generating the ARM template from Farmer (`Writer.quickWrite`) and then manually running what-if via the az CLI.

I'm always careful when porting from ARM to Farmer just in case something is generated differently.

Having said all this, I've looked at custom domains and it doesn't look too bad, so maybe create an issue for it so that someone can add it (a sample ARM is [here](https://vivien-chevallier.com/Articles/adding-a-custom-domain-name-to-an-app-with-arm-template-in-azure-app-service)).

**Comment by Lewiszz** [comment]
Thanks, I will experiment a bit more and let you know what comes out!

**Comment by TheRSP** [comment]
If it helps, we have many web apps deployed using farmer but they have custom domains and TLS settings configured in Azure portal - these aren't overwritten when we redeploy. 

Because the `hostNameBindings` and `certificates` are separate resources, these don't appear to be affected when we redeploy the `sites` resource

**Comment by Lewiszz** [comment]
Thanks a lot! I didn't get to do all the testing I wanted, so good to know that it will probably work for us too when we need to.
