### ISSUE TITLE
Support templates with variables

### ISSUE THREAD

**Issue by panesofglass** [CompositionalIT/farmer#8]
I could see this being really useful for creating reusable templates to add to an Azure .org for repeat deployments with different names. I get that is not the primary use case, but this would certainly help that use case.

**Comment by isaacabraham** [comment]
Hey both :-)

The very first version actually had support for three types of "values": Literals, Variables and Parameters. When the ARM template was generated, the outputter would correctly splice out the correct reference. We also had `variable` and `parameter` keywords to allow easily setting them.

However, this had several costs:

1. Codebase was made more complex.
2. API surface area was more complex e.g. you had to specify things like `Literal "xyz"` instead of just `"xyz"` because any value could be referenced by any of the three types.
3. Supported things like the expression capabilities inside the ARM template so that you could use things like `concat` inside e.g. a variable that's dependent on another variable. We even had a simple set of functions that would emit value ARM expressions.

Where I'm thinking now is slightly different, and is basically what you've both highlighted: we don't support ARM variables or parameters at all, and instead would recommend putting Farmer as part of your build script to generate the ARM template as part of the build / release process (rather than committing into source control). This has several benefits:

1. Simplifies the code base.
2. Instead of using the error prone and limited expression capabilities of ARM templates, you can use a proper programming language for conditional logic for creating the ARM template.
3. Deployments e.g. inside the Azure Portal are much easier to read because there are no placeholders or variables but just values.

Currently our thinking is the only place we would support parameters is for securestrings for e.g. database passwords which you don't want showing up in the Azure Portal deployments area. In such a case for e.g. the current SQL Azure codebase, we actually generate a securestring parameter with a generated name based on the sql database.

**Comment by BrianVallelunga** [comment]
Thanks for the history here. I just went through a similar issue with an Angular project. Angular supports different environments via different json environment files (environment.dev.json, environment.prod.json, etc) but you have to rebuild the entire app each time, which can take 5 minutes on some slower build machines.

More than the time involved, it breaks the build once, deploy multiple times process that most build systems use. I do see the appeal of a simpler code-base and this script generation is trivially fast, so I'll have to figure out how I can best make this work. Right now I'm leaning towards have the build process just create all the environment files at once and then using the appropriate one.

I'm going to try and recreate my Azure environment with Farmer and see if there are any pain points and I'll give more feedback based on that.

**Comment by panesofglass** [comment]
Makes sense. I’m facing a need to publish something to the marketplace, and that is why I was suggesting this.

**Comment by isaacabraham** [comment]
@panesofglass you could also use Farmer as a simple way to get the ARM template "up and running" as a one-off task, and then move over to manually crafting the ARM template as needed?

**Comment by isaacabraham** [comment]
Closing this unless there's any tangible ask / feature request / issue to come out of this?
