### ISSUE TITLE
Support Azure Container Apps

### ISSUE THREAD

**Issue by forki** [CompositionalIT/farmer#809]
Example ARM: https://docs.microsoft.com/de-de/azure/container-apps/microservices-dapr-azure-resource-manager?tabs=bash#create-azure-resource-manager-arm-templates
Example for Scaling: https://docs.microsoft.com/de-de/azure/container-apps/scale-app#event-driven

**Comment by forki** [comment]
API spec: https://docs.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec

**Comment by isaacabraham** [comment]
Will probably need a full list of the KEDA scaling rules e.g. it looks like queue-based rules can be many implementations of which service bus is only one.

**Comment by isaacabraham** [comment]
But we could start simple just HTTP / Mem / CPU rules to start.

Would you have any interest in providing the building block for this - even the "anonymous record / function" stage of building a supported resource; we could then convert this into a full thing.

**Comment by forki** [comment]
>even the "anonymous record / function" stage of building a supported resource

working on it

**Comment by forki** [comment]
Sneak Peek
![image](https://user-images.githubusercontent.com/57396/141787178-afad0b71-57c4-4977-9482-979add822aaa.png)

**Comment by isaacabraham** [comment]
Coming along nicely! I think that you might want to consider closer integration of the different components (in the same way that we do for k8s containers or app service) e.g.:

1. Ability to auto-create an environment without supplying one, and / or ability to create an environment with a collection of container apps e.g.

```fsharp
let x =
    containerAppEnvironment {
        add_apps [
            containerApp {
                ....
            }
        ]
    }
````

2. Helper keywords to connect other azure resources e.g. `connect_servicebus_queue` which does the boilerplate in a consistent, well-defined way using a strongly-typed service bus queue config value.
3. Consider changing scaling to `add_scale_rule` which takes in a DU of the scale type.
4. Parameters should never normally be required to be explicitly supplied e.g. in webapp, we have `add_secret_setting` (or something like that) in which you just specify the name of the setting and we automatically create a parameter based on a naming convention (basically what you've done here).
5. Consider min/max replicas as a tuple rather than two keywords? I can't imagine many people will only want to set only one.

**Comment by forki** [comment]
how can I get the outer containerAppEnvironment ID?

**Comment by isaacabraham** [comment]
Depends on the ARM template - hopefully there's an expression available on the environment to do that. You must have that already because you're passing in `kubeEnvironment` so clearly you already are able to connect the two together? I'm just proposing to change the end-user experience from an API point of view. It would still emit the same ARM.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/141798482-5017cf33-8126-4dba-ac5d-978364d57c0e.png)
